// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTrj_Iw9XIgpZlakYq7WYMb854TadY1a0',
    appId: '1:252689987865:web:f23659e8d126009249ad88',
    messagingSenderId: '252689987865',
    projectId: 'stadium-d5b5f',
    authDomain: 'stadium-d5b5f.firebaseapp.com',
    storageBucket: 'stadium-d5b5f.firebasestorage.app',
    measurementId: 'G-PSWVTHTE5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjPTavTVpOmKlFsR1sfKNNSSAzeCQpXYI',
    appId: '1:252689987865:android:9d652fd2baa5aed749ad88',
    messagingSenderId: '252689987865',
    projectId: 'stadium-d5b5f',
    storageBucket: 'stadium-d5b5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ2XcCVy1Yala4D9YbEvtpPkr1dGZBN7Q',
    appId: '1:252689987865:ios:9b92a92ddb739e7e49ad88',
    messagingSenderId: '252689987865',
    projectId: 'stadium-d5b5f',
    storageBucket: 'stadium-d5b5f.firebasestorage.app',
    iosClientId: '252689987865-7b22s35qcm2m17f3tqdhgls8g72aicfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.stadiumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ2XcCVy1Yala4D9YbEvtpPkr1dGZBN7Q',
    appId: '1:252689987865:ios:9b92a92ddb739e7e49ad88',
    messagingSenderId: '252689987865',
    projectId: 'stadium-d5b5f',
    storageBucket: 'stadium-d5b5f.firebasestorage.app',
    iosClientId: '252689987865-7b22s35qcm2m17f3tqdhgls8g72aicfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.stadiumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTrj_Iw9XIgpZlakYq7WYMb854TadY1a0',
    appId: '1:252689987865:web:41878feeb493e20649ad88',
    messagingSenderId: '252689987865',
    projectId: 'stadium-d5b5f',
    authDomain: 'stadium-d5b5f.firebaseapp.com',
    storageBucket: 'stadium-d5b5f.firebasestorage.app',
    measurementId: 'G-7P7NFV7R5R',
  );

}